"""Section 3.1 Leg Database builder for ballistic Lambert legs.

A "leg" is one heliocentric arc connecting two consecutive encounter nodes
(departure body at stage i → arrival body at stage i+1).  Each leg row stores
the two v-infinity vectors (departure and arrival) needed to patch into the
surrounding flyby/DSM maneuvers.

Index glossary
--------------
IL  : Leg index   — sequential integer assigned to each leg row within one stage (0-based).
ID  : Departure encounter index (IE) — points into EncounterDB for the departure node.
IA  : Arrival encounter index (IE)   — points into EncounterDB for the arrival node.
tof : Time of flight — elapsed time from departure to arrival [seconds].
vinf: v-infinity     — spacecraft velocity relative to the body at encounter [km/s].
dv  : Delta-v        — impulsive velocity change, here from a DSM maneuver [km/s].
eta : DSM split fraction — fraction of tof at which the DSM is placed (0 = departure, 1 = arrival).

See NOTATION.md for the full glossary (stage kinds, lev_type sign pairs,
lambert_hz, and the IL-is-stage-scoped caveat).

What `LegDatabase` stores:
  `IL`, `ID`, `IA` integer arrays plus `vinfD_km_s`, `vinfA_km_s` as `(N,3)`
  float arrays, along with per-row signed `n_rev`, DSM leveraging magnitude
  `dv_lev_km_s`, and DSM split fraction `eta_lev`.

Deterministic ordering:
  Candidates are generated by departure entries sorted by `(t_et, IE)` and, for each
  departure, arrivals sorted by `(t_et, IE)`. `IL` is assigned sequentially from 0.

Filters:
  1) time-of-flight filter keeps only `dt_s > dt_positive_tol_s` and
     `tof_min_s <= dt_s <= tof_max_s` (with `+/-inf` treated as unbounded),
  2) `v_infinity` filter keeps only rows whose `||vinfD||` and `||vinfA||` are inside
     configured `[min,max]` bounds,
  3) Lambert failures are skipped.

Current coverage of leg types:
    - lambert
    - resonant
    - DSM (leveraging) with solve_arc objective types
    - null leg

NOT implemented yet:
    - rendezvous leg
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field
import inspect
from pathlib import Path
import sys
from typing import Callable, Dict, Iterator, List, Optional, Sequence, Tuple

import numpy as np
import spiceypy as spice
from numba import njit

import time

from star.constants import DEFAULT_FRAME, DEFAULT_OBSERVER, get_gm
from star.constants.time import et_seconds_to_j2000_days, j2000_days_to_et_seconds
from star.encounter_database import (
    EncounterDB,
    EncounterDBConfig,
    EncounterEntry,
    EncounterStageConfig,
    tighten_stage_time_bounds_days,
    build_encounter_database,
)
from star.lambert import lambert_batch

sys.modules.setdefault("leg_database", sys.modules[__name__])

# Minimum elapsed time [s] between progress prints (change to taste).
_PROGRESS_INTERVAL_S: float = 300.0

@dataclass(frozen=True)
class LegBuildConfig:
    """Configuration for building one ballistic leg database.
    """

    leg_stage_id: int
    dep_stage_id: int
    arr_stage_id: int

    tof_min_s: float
    tof_max_s: float

    vinfD_bounds_km_s: Tuple[float, float] = (-np.inf, np.inf)
    vinfA_bounds_km_s: Tuple[float, float] = (-np.inf, np.inf)

    lambert_mu_km3_s2: float = 1.3271244004193938e11
    # NOTE: branch selector is currently ignored by the current solver path.
    lambert_num_solutions: str = "short"
    # Maximum revolution count for Lambert solve; the solver sweeps 0..n via sweep_rev.
    lambert_nrev_max: int = 0
    # Direction selector for Lambert solve: +1 (ccw), -1 (cw), 0 (both).
    lambert_hz: int = 1
    # DSM leveraging controls [km/s]: if max <= 0, keep Lambert-only rows.
    dvlev_max_km_s: float = 0.0
    delta_dvlev_km_s: float = 0.0
    # Relaxed pre-DSM seed screening margin [km/s]; final vlim remains exact.
    vinf_margin_pre_filter_km_s: float = 10.0
    # Leveraging type selector for solve_arc objective type 1.
    lev_type: Tuple[str, ...] = ("+-", "-+")
    # Optional resonant-leg expansion off near-resonant Lambert seeds.
    resonant_enabled: bool = False
    resonant_angle_tol_deg: float = 4.0
    resonant_dvinf_km_s: float = 0.1
    resonant_crank_angles_rad: Tuple[float, ...] = ()

    parallelism: Optional[int] = None
    dt_positive_tol_s: float = 1e-6
    max_failure_frac: Optional[float] = None

    debug: bool = False
    chunk_size: int = 20000

    leg_filter: Optional[Callable[..., np.ndarray]] = None


@dataclass
class LegDatabase:
    """Leg database for one stage transition (departure stage → arrival stage).

    Each row represents one valid arc candidate.  Arrays are aligned: row k of
    `IL`, `ID`, `IA`, `vinfD_km_s`, etc. all refer to the same candidate leg.

    Fields:
        IL: Leg indices [int array, shape (N,)] — unique ID within this stage.
        stage_id: Leg stage index (equals departure stage index).
        ID: Departure encounter indices [int array, shape (N,)] — index into EncounterDB.
        IA: Arrival encounter indices [int array, shape (N,)] — index into EncounterDB.
        vinfD_km_s: Departure v-infinity vectors [km/s], shape (N, 3).
        vinfA_km_s: Arrival v-infinity vectors [km/s], shape (N, 3).
        n_rev: Signed Lambert revolution count per row — positive = prograde multi-rev.
        dv_lev_km_s: DSM leveraging delta-v magnitude [km/s] per row (0 if no DSM).
        eta_lev: DSM placement fraction along the arc [0, 1] per row (0 if no DSM).
    """

    IL: np.ndarray
    stage_id: int
    ID: np.ndarray
    IA: np.ndarray

    vinfD_km_s: np.ndarray
    vinfA_km_s: np.ndarray

    n_rev: np.ndarray

    # impulsive DSM fields: 
    # Applied DSM leveraging magnitude [km/s] per leg row.
    dv_lev_km_s: np.ndarray = field(default_factory=lambda: np.empty(0, dtype=float))
    # DSM split-arc fraction eta in [0,1] per leg row.
    eta_lev: np.ndarray = field(default_factory=lambda: np.empty(0, dtype=float))

    @property
    def leg_id(self) -> np.ndarray:
        """Alias for `IL`."""
        return self.IL


def solve_lambert(
    r1_km: np.ndarray,
    r2_km: np.ndarray,
    dt_s: np.ndarray,
    mu_km3_s2: float,
    *,
    n_rev_max: int = 0,
    hz: int = 1,
    sweep_rev: bool = True,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Solve Lambert transfer(s) in km/km/s and return expanded rows.

    Args:
        r1_km: Departure positions [km], shape `(3,)` or `(N,3)`.
        r2_km: Arrival positions [km], shape `(3,)` or `(N,3)`.
        dt_s: Time of flight [seconds], scalar or shape `(N,)`.
        mu_km3_s2: Gravitational parameter [km^3/s^2].
        n_rev_max: Maximum revolution count [int >= 0].
        hz: Direction selector (`+1` ccw, `-1` cw, `0` both).
        sweep_rev: If True, solve all rev counts from 0..n_rev_max.

    Returns:
        v1_km_s: Departure transfer velocities [km/s], shape `(M,3)`.
        v2_km_s: Arrival transfer velocities [km/s], shape `(M,3)`.
        nrev_signed: Signed rev label per output row [shape `(M,)`].
        index: Source-row index into input rows [shape `(M,)`].
    """

    r1_array = np.asarray(r1_km, dtype=float)
    r2_array = np.asarray(r2_km, dtype=float)
    dt_array = np.asarray(dt_s, dtype=float)

    scalar_input = r1_array.ndim == 1
    if scalar_input:
        r1_array = r1_array.reshape(1, 3)
        r2_array = r2_array.reshape(1, 3)

    if r1_array.ndim != 2 or r2_array.ndim != 2 or r1_array.shape[1] != 3 or r2_array.shape[1] != 3:
        raise ValueError("r1_km and r2_km must have shape (3,) or (N,3).")

    num_rows = r1_array.shape[0]
    if dt_array.ndim == 0:
        dt_array = np.full(num_rows, float(dt_array), dtype=float)
    if dt_array.shape != (num_rows,):
        raise ValueError("dt_s must be scalar or shape (N,) matching the row count of r1_km/r2_km.")

    v1_km_s, v2_km_s, _, nrev_signed, index = lambert_batch(
        r1_array,
        r2_array,
        dt_array,
        mu=float(mu_km3_s2),
        N=int(n_rev_max),
        hz=int(hz),
        sweep_rev=bool(sweep_rev),
    )

    v1_array = np.asarray(v1_km_s, dtype=float)
    v2_array = np.asarray(v2_km_s, dtype=float)
    nrev_array = np.asarray(nrev_signed, dtype=np.int64).reshape(-1)
    idx_array = np.asarray(index, dtype=np.int64).reshape(-1)

    if scalar_input:
        return (
            v1_array.reshape(-1, 3),
            v2_array.reshape(-1, 3),
            nrev_array,
            idx_array,
        )
    return v1_array.reshape(-1, 3), v2_array.reshape(-1, 3), nrev_array, idx_array


def _collect_stage_arrays(enc_db: EncounterDB, stage_id: int) -> Dict[str, np.ndarray]:
    """Extract stage entries sorted by `(t_et, IE)` for deterministic traversal."""

    stage_entries: List[EncounterEntry] = [entry for entry in enc_db.entries if int(entry.stage_id) == int(stage_id)]
    if not stage_entries:
        raise ValueError(f"No encounter entries found for stage_id={stage_id}.")

    stage_entries_sorted = sorted(stage_entries, key=lambda entry: (float(entry.t_et), int(entry.IE)))

    n = len(stage_entries_sorted)
    IE_arr = np.empty(n, dtype=np.int64)
    t_et_arr = np.empty(n, dtype=float)
    r_km_arr = np.empty((n, 3), dtype=float)
    v_km_s_arr = np.empty((n, 3), dtype=float)
    for i, e in enumerate(stage_entries_sorted):
        IE_arr[i] = e.IE
        t_et_arr[i] = e.t_et
        r_km_arr[i] = e.r_km
        v_km_s_arr[i] = e.v_km_s
    return {"IE": IE_arr, "t_et": t_et_arr, "r_km": r_km_arr, "v_km_s": v_km_s_arr}


def _get_stage_arrays(
    enc_db: EncounterDB,
    stage_id: int,
    stage_arrays_cache: Optional[Dict[int, Dict[str, np.ndarray]]],
) -> Dict[str, np.ndarray]:
    """Return stage arrays, optionally reusing a caller-owned cache."""

    stage_id_int = int(stage_id)
    if stage_arrays_cache is None:
        return _collect_stage_arrays(enc_db, stage_id_int)

    cached = stage_arrays_cache.get(stage_id_int)
    if cached is None:
        cached = _collect_stage_arrays(enc_db, stage_id_int)
        stage_arrays_cache[stage_id_int] = cached
    return cached


def _apply_custom_leg_filter(
    cfg: LegBuildConfig,
    dep_data: Dict[str, np.ndarray],
    arr_data: Dict[str, np.ndarray],
    row_arrays: Dict[str, np.ndarray],
) -> Dict[str, np.ndarray]:
    """Apply one optional custom leg filter to aligned row arrays."""

    if cfg.leg_filter is None:
        return row_arrays

    row_count = int(np.asarray(row_arrays["ID"], dtype=np.int64).size)
    if row_count == 0:
        return row_arrays

    dep_ie = np.asarray(row_arrays["ID"], dtype=np.int64).ravel()
    arr_ie = np.asarray(row_arrays["IA"], dtype=np.int64).ravel()

    dep_ie_order = np.argsort(dep_data["IE"])
    dep_ie_sorted = dep_data["IE"][dep_ie_order]
    dep_pos = np.searchsorted(dep_ie_sorted, dep_ie)
    if np.any(dep_pos >= dep_ie_sorted.size) or not np.all(dep_ie_sorted[dep_pos] == dep_ie):
        raise ValueError("Custom leg filter received departure encounter IDs not present in the departure stage.")
    dep_rows = dep_ie_order[dep_pos]

    arr_ie_order = np.argsort(arr_data["IE"])
    arr_ie_sorted = arr_data["IE"][arr_ie_order]
    arr_pos = np.searchsorted(arr_ie_sorted, arr_ie)
    if np.any(arr_pos >= arr_ie_sorted.size) or not np.all(arr_ie_sorted[arr_pos] == arr_ie):
        raise ValueError("Custom leg filter received arrival encounter IDs not present in the arrival stage.")
    arr_rows = arr_ie_order[arr_pos]

    filter_kwargs: Dict[str, np.ndarray] = {}
    try:
        signature = inspect.signature(cfg.leg_filter)
    except (TypeError, ValueError):
        signature = None

    if signature is not None:
        parameters = signature.parameters
        accepts_kwargs = any(param.kind == inspect.Parameter.VAR_KEYWORD for param in parameters.values())
        # Keep legacy filters working while allowing newer filters to opt into time data.
        if accepts_kwargs or "dep_t_et_s" in parameters:
            filter_kwargs["dep_t_et_s"] = dep_data["t_et"][dep_rows]
        if accepts_kwargs or "arr_t_et_s" in parameters:
            filter_kwargs["arr_t_et_s"] = arr_data["t_et"][arr_rows]

    custom_keep = cfg.leg_filter(
        cfg.leg_stage_id,
        np.asarray(row_arrays["vinfD_km_s"], dtype=float),
        np.asarray(row_arrays["vinfA_km_s"], dtype=float),
        dep_data["r_km"][dep_rows],
        dep_data["v_km_s"][dep_rows],
        arr_data["r_km"][arr_rows],
        arr_data["v_km_s"][arr_rows],
        **filter_kwargs,
    )
    custom_keep = np.asarray(custom_keep, dtype=bool).ravel()
    if custom_keep.size != row_count:
        raise ValueError(f"Custom leg filter returned {custom_keep.size} rows for {row_count} input rows.")

    return {
        key: np.asarray(value)[custom_keep]
        for key, value in row_arrays.items()
    }


@njit(cache=True)
def _count_candidate_pairs_jit(
    dep_t_et_s: np.ndarray,
    arr_t_et_s: np.ndarray,
    lower_dt_s: float,
    upper_dt_s: float,
    lower_dt_strict: bool,
    use_tof_max: bool,
) -> np.ndarray:
    """Count feasible arrival rows per departure row."""

    num_dep = dep_t_et_s.shape[0]
    num_arr = arr_t_et_s.shape[0]
    counts = np.zeros(num_dep, dtype=np.int64)

    right_default = num_arr
    for dep_row_index in range(num_dep):
        t_dep = dep_t_et_s[dep_row_index]
        if lower_dt_strict:
            left = int(np.searchsorted(arr_t_et_s, t_dep + lower_dt_s, side="right"))
        else:
            left = int(np.searchsorted(arr_t_et_s, t_dep + lower_dt_s, side="left"))
        if use_tof_max:
            right = int(np.searchsorted(arr_t_et_s, t_dep + upper_dt_s, side="right"))
        else:
            right = right_default
        if right > left:
            counts[dep_row_index] = right - left

    return counts


def _prepare_candidate_pair_counts(
    dep_t_et_s: np.ndarray,
    arr_t_et_s: np.ndarray,
    tof_min_s: float,
    tof_max_s: float,
    dt_positive_tol_s: float,
) -> Tuple[np.ndarray, np.ndarray, float, float, bool, bool, np.ndarray]:
    """Normalize candidate-pair inputs and count feasible arrivals per departure row."""

    dep_t_arr = np.asarray(dep_t_et_s, dtype=float)
    arr_t_arr = np.asarray(arr_t_et_s, dtype=float)
    if dep_t_arr.ndim != 1 or arr_t_arr.ndim != 1:
        raise ValueError("dep_t_et_s and arr_t_et_s must be one-dimensional arrays.")

    dep_t_arr = np.ascontiguousarray(dep_t_arr.reshape(-1))
    arr_t_arr = np.ascontiguousarray(arr_t_arr.reshape(-1))

    dt_positive_tol = float(dt_positive_tol_s)
    tof_min = float(tof_min_s)
    lower_dt_s = max(dt_positive_tol, tof_min) if np.isfinite(tof_min_s) else dt_positive_tol
    lower_dt_strict = (not np.isfinite(tof_min_s)) or (tof_min <= dt_positive_tol)
    use_tof_max = bool(np.isfinite(tof_max_s))
    upper_dt_s = float(tof_max_s) if use_tof_max else 0.0

    counts = _count_candidate_pairs_jit(
        dep_t_arr,
        arr_t_arr,
        float(lower_dt_s),
        upper_dt_s,
        bool(lower_dt_strict),
        use_tof_max,
    )
    return dep_t_arr, arr_t_arr, float(lower_dt_s), upper_dt_s, bool(lower_dt_strict), use_tof_max, counts


def _iter_candidate_pair_chunks_from_counts(
    dep_t_et_s: np.ndarray,
    arr_t_et_s: np.ndarray,
    lower_dt_s: float,
    lower_dt_strict: bool,
    counts: np.ndarray,
    *,
    chunk_size: int,
) -> Iterator[Tuple[np.ndarray, np.ndarray, np.ndarray]]:
    """Yield candidate pairs in the same flattened order as `_generate_candidate_pairs`."""

    chunk_size_int = max(1, int(chunk_size))
    dep_parts: List[np.ndarray] = []
    arr_parts: List[np.ndarray] = []
    dt_parts: List[np.ndarray] = []
    buffered_rows = 0

    def _flush_parts() -> Optional[Tuple[np.ndarray, np.ndarray, np.ndarray]]:
        nonlocal buffered_rows
        if buffered_rows <= 0:
            return None

        if len(dep_parts) == 1:
            dep_chunk = dep_parts[0]
            arr_chunk = arr_parts[0]
            dt_chunk = dt_parts[0]
        else:
            dep_chunk = np.concatenate(dep_parts, axis=0)
            arr_chunk = np.concatenate(arr_parts, axis=0)
            dt_chunk = np.concatenate(dt_parts, axis=0)

        dep_parts.clear()
        arr_parts.clear()
        dt_parts.clear()
        buffered_rows = 0
        return dep_chunk, arr_chunk, dt_chunk

    for dep_row_index in range(dep_t_et_s.shape[0]):
        pair_count = int(counts[dep_row_index])
        if pair_count <= 0:
            continue

        t_dep = float(dep_t_et_s[dep_row_index])
        left_side = "right" if bool(lower_dt_strict) else "left"
        left = int(np.searchsorted(arr_t_et_s, t_dep + float(lower_dt_s), side=left_side))
        right = left + pair_count
        arr_row_index = left

        while arr_row_index < right:
            rows_remaining = int(chunk_size_int - buffered_rows)
            take = min(rows_remaining, int(right - arr_row_index))
            if take <= 0:
                chunk = _flush_parts()
                if chunk is not None:
                    yield chunk
                continue

            arr_rows = np.arange(arr_row_index, arr_row_index + take, dtype=np.int64)
            dep_rows = np.full(take, int(dep_row_index), dtype=np.int64)
            dt_rows = arr_t_et_s[arr_rows] - t_dep

            dep_parts.append(dep_rows)
            arr_parts.append(arr_rows)
            dt_parts.append(dt_rows)
            buffered_rows += take
            arr_row_index += take

            if buffered_rows >= chunk_size_int:
                chunk = _flush_parts()
                if chunk is not None:
                    yield chunk

    chunk = _flush_parts()
    if chunk is not None:
        yield chunk

def _solve_chunk_with_split(
    r1_km: np.ndarray,
    r2_km: np.ndarray,
    dt_s: np.ndarray,
    cfg: LegBuildConfig,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Solve one chunk and recursively split on failures to salvage valid rows.

    Returns expanded Lambert outputs plus source-row indices into this chunk.
    """

    num_rows = dt_s.shape[0]
    if num_rows == 0:
        empty_v = np.empty((0, 3), dtype=float)
        empty_i = np.empty(0, dtype=np.int64)
        return empty_v, empty_v.copy(), empty_i, empty_i

    v1_parts: List[np.ndarray] = []
    v2_parts: List[np.ndarray] = []
    nrev_parts: List[np.ndarray] = []
    src_idx_parts: List[np.ndarray] = []

    def _recurse(local_indices: np.ndarray) -> None:
        if local_indices.size == 0:
            return

        r1_local = r1_km[local_indices]
        r2_local = r2_km[local_indices]
        dt_local = dt_s[local_indices]

        try:
            v1_local, v2_local, nrev_local, idx_local = solve_lambert(
                r1_local,
                r2_local,
                dt_local,
                cfg.lambert_mu_km3_s2,
                n_rev_max=int(cfg.lambert_nrev_max),
                hz=int(cfg.lambert_hz),
                sweep_rev=True,
            )
            v1_local = np.asarray(v1_local, dtype=float).reshape(-1, 3)
            v2_local = np.asarray(v2_local, dtype=float).reshape(-1, 3)
            nrev_local = np.asarray(nrev_local, dtype=np.int64).reshape(-1)
            idx_local = np.asarray(idx_local, dtype=np.int64).reshape(-1)

            if idx_local.size == 0:
                return

            finite_local = np.all(np.isfinite(v1_local), axis=1) & np.all(np.isfinite(v2_local), axis=1)
            if np.any(finite_local):
                v1_parts.append(v1_local[finite_local])
                v2_parts.append(v2_local[finite_local])
                nrev_parts.append(nrev_local[finite_local])
                src_idx_parts.append(local_indices[idx_local[finite_local]])

        except Exception:
            if local_indices.size == 1:
                return

            mid = local_indices.size // 2
            _recurse(local_indices[:mid])
            _recurse(local_indices[mid:])

    _recurse(np.arange(num_rows, dtype=np.int64))
    if not v1_parts:
        empty_v = np.empty((0, 3), dtype=float)
        empty_i = np.empty(0, dtype=np.int64)
        return empty_v, empty_v.copy(), empty_i, empty_i

    return (
        np.concatenate(v1_parts, axis=0),
        np.concatenate(v2_parts, axis=0),
        np.concatenate(nrev_parts, axis=0),
        np.concatenate(src_idx_parts, axis=0),
    )


def _solve_lambert_candidates(
    r1_km: np.ndarray,
    r2_km: np.ndarray,
    dt_s: np.ndarray,
    cfg: LegBuildConfig,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Solve Lambert for all candidate rows with optional chunk-level parallelism.

    Returns expanded Lambert rows plus source-row indices into the candidate arrays.
    """

    num_rows = dt_s.shape[0]
    if num_rows == 0:
        empty_vec = np.empty((0, 3), dtype=float)
        empty_i = np.empty(0, dtype=np.int64)
        return empty_vec, empty_vec, empty_i, empty_i

    chunk_size = max(1, int(cfg.chunk_size))
    chunk_ranges: List[Tuple[int, int]] = [
        (start, min(start + chunk_size, num_rows)) for start in range(0, num_rows, chunk_size)
    ]

    v1_parts: List[np.ndarray] = []
    v2_parts: List[np.ndarray] = []
    nrev_parts: List[np.ndarray] = []
    src_parts: List[np.ndarray] = []

    if cfg.parallelism is None or int(cfg.parallelism) <= 1 or len(chunk_ranges) == 1:
        n_chunks = len(chunk_ranges)
        _last_print_t = time.monotonic()
        for chunk_i, (start, end) in enumerate(chunk_ranges):
            _now = time.monotonic()
            if _now - _last_print_t >= _PROGRESS_INTERVAL_S:
                _last_print_t = _now
                pct = 100 * start // max(num_rows, 1)
                print(f"\r  Lambert {chunk_i+1:3d}/{n_chunks:3d} | {start:>8,}/{num_rows:>8,} pairs | {pct:3d}%", end="", flush=True)
            v1_chunk, v2_chunk, nrev_chunk, src_chunk = _solve_chunk_with_split(
                r1_km[start:end],
                r2_km[start:end],
                dt_s[start:end],
                cfg,
            )
            if src_chunk.size:
                v1_parts.append(v1_chunk)
                v2_parts.append(v2_chunk)
                nrev_parts.append(nrev_chunk)
                src_parts.append(src_chunk + int(start))
    else:
        workers = max(1, int(cfg.parallelism))
        n_chunks = len(chunk_ranges)

        def _worker(args: Tuple[int, int]) -> Tuple[int, int, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
            start, end = args
            v1_chunk, v2_chunk, nrev_chunk, src_chunk = _solve_chunk_with_split(
                r1_km[start:end],
                r2_km[start:end],
                dt_s[start:end],
                cfg,
            )
            return start, end, v1_chunk, v2_chunk, nrev_chunk, src_chunk

        _last_print_t = time.monotonic()
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = [executor.submit(_worker, chunk) for chunk in chunk_ranges]
            for chunk_i, future in enumerate(futures):
                start, end, v1_chunk, v2_chunk, nrev_chunk, src_chunk = future.result()
                _now = time.monotonic()
                if _now - _last_print_t >= _PROGRESS_INTERVAL_S:
                    _last_print_t = _now
                    pct = 100 * chunk_i // max(n_chunks, 1)
                    print(f"\r  Lambert {chunk_i+1:3d}/{n_chunks:3d} | {start:>8,}/{num_rows:>8,} pairs | {pct:3d}% [parallel]", end="", flush=True)
                if src_chunk.size:
                    v1_parts.append(v1_chunk)
                    v2_parts.append(v2_chunk)
                    nrev_parts.append(nrev_chunk)
                    src_parts.append(src_chunk + int(start))

    if not v1_parts:
        empty_vec = np.empty((0, 3), dtype=float)
        empty_i = np.empty(0, dtype=np.int64)
        return empty_vec, empty_vec, empty_i, empty_i

    return (
        np.concatenate(v1_parts, axis=0),
        np.concatenate(v2_parts, axis=0),
        np.concatenate(nrev_parts, axis=0),
        np.concatenate(src_parts, axis=0),
    )


def _empty_leg_db(stage_id: int) -> LegDatabase:
    """Create an empty `LegDatabase` with correctly-shaped arrays."""

    empty_i = np.empty(0, dtype=np.int64)
    empty_f = np.empty(0, dtype=float)
    empty_v = np.empty((0, 3), dtype=float)
    return LegDatabase(
        IL=empty_i,
        stage_id=int(stage_id),
        ID=empty_i,
        IA=empty_i,
        vinfD_km_s=empty_v,
        vinfA_km_s=empty_v,
        n_rev=empty_i,
        dv_lev_km_s=empty_f,
        eta_lev=empty_f,
    )


def _build_dv_lev_grid_km_s(max_km_s: float, delta_km_s: float, *, tol: float = 1e-12) -> np.ndarray:
    """Build non-zero DSM leveraging grid [km/s] up to max (inclusive when possible)."""

    dv_max = float(max_km_s)
    if not np.isfinite(dv_max) or dv_max < 0.0:
        raise ValueError("dvlev_max_km_s must be finite and >= 0.")
    if dv_max <= float(tol):
        return np.empty(0, dtype=float)

    dv_step = float(delta_km_s)
    if not np.isfinite(dv_step) or dv_step <= 0.0:
        raise ValueError("delta_dvlev_km_s must be finite and > 0 when dvlev_max_km_s > 0.")

    n_full = int(np.floor((dv_max + float(tol)) / dv_step))
    if n_full <= 0:
        grid = np.asarray([dv_max], dtype=float)
    else:
        grid = dv_step * np.arange(1, n_full + 1, dtype=float)
        grid = grid[grid <= dv_max + float(tol)]
        if grid.size == 0 or (dv_max - float(grid[-1])) > float(tol):
            grid = np.concatenate((grid, np.asarray([dv_max], dtype=float)))
        elif abs(float(grid[-1]) - dv_max) <= float(tol):
            grid[-1] = dv_max

    return np.unique(np.asarray(grid, dtype=float))


def _relaxed_pre_filter_vinf_max_km_s(vinf_max_km_s: float, margin_km_s: float) -> float:
    """Return the pre-DSM max vinf bound; final saved rows still use exact vlim."""

    margin = float(margin_km_s)
    if not np.isfinite(margin) or margin < 0.0:
        raise ValueError("vinf_margin_pre_filter_km_s must be finite and >= 0.")
    if np.isfinite(vinf_max_km_s):
        return float(vinf_max_km_s) + margin
    return 1.0e9


def _process_lambert_chunk(
    *,
    dep_data: Dict[str, np.ndarray],
    arr_data: Dict[str, np.ndarray],
    dep_rows_chunk: np.ndarray,
    arr_rows_chunk: np.ndarray,
    dt_candidates_chunk_s: np.ndarray,
    r_dep_km: np.ndarray,
    r_arr_km: np.ndarray,
    v_body_dep_km_s: np.ndarray,
    v_body_arr_km_s: np.ndarray,
    v_dep_km_s: np.ndarray,
    v_arr_km_s: np.ndarray,
    nrev_signed_eval: np.ndarray,
    source_idx: np.ndarray,
    cfg: LegBuildConfig,
    dV_lev_grid_km_s: np.ndarray,
    vinfD_min_km_s: float,
    vinfD_max_km_s: float,
    vinfA_min_km_s: float,
    vinfA_max_km_s: float,
) -> Optional[Dict[str, np.ndarray]]:
    """Convert one solved Lambert chunk into kept leg-database rows."""

    source_idx = np.asarray(source_idx, dtype=np.int64)
    if source_idx.size == 0:
        return None

    nrev_signed_eval = np.asarray(nrev_signed_eval, dtype=np.int64)

    dep_rows_seed = dep_rows_chunk[source_idx]
    arr_rows_seed = arr_rows_chunk[source_idx]
    dt_seed_s = dt_candidates_chunk_s[source_idx]
    r_dep_seed_km = r_dep_km[source_idx]
    r_arr_seed_km = r_arr_km[source_idx]
    v_body_dep_seed_km_s = v_body_dep_km_s[source_idx]
    v_body_arr_seed_km_s = v_body_arr_km_s[source_idx]

    # Optional solve_arc expansion: preserve Lambert-only behavior when dV grid is empty.
    if dV_lev_grid_km_s.size > 0:
        from star.maneuver_placement import solve_arc

        t_dep_seed_s = dep_data["t_et"][dep_rows_seed]
        t_arr_seed_s = arr_data["t_et"][arr_rows_seed]

        max_vinf0_solve_arc = _relaxed_pre_filter_vinf_max_km_s(
            vinfD_max_km_s,
            cfg.vinf_margin_pre_filter_km_s,
        )
        max_vinff_solve_arc = _relaxed_pre_filter_vinf_max_km_s(
            vinfA_max_km_s,
            cfg.vinf_margin_pre_filter_km_s,
        )

        vinf0_seed_km_s = np.linalg.norm(v_dep_km_s - v_body_dep_seed_km_s, axis=1)
        vinff_seed_km_s = np.linalg.norm(v_arr_km_s - v_body_arr_seed_km_s, axis=1)
        raw_seed_keep = (
            (vinf0_seed_km_s <= max_vinf0_solve_arc)
            & (vinff_seed_km_s <= max_vinff_solve_arc)
        )
        if not np.any(raw_seed_keep):
            return None

        (
            eta_store,
            dV_lev_all,
            vinfD_km_s_all,
            vinfA_km_s_all,
            _lev_store,
            arc_store,
            _seed_store,
        ) = solve_arc(
            r_dep_seed_km,
            r_arr_seed_km,
            v_body_dep_seed_km_s,
            v_body_arr_seed_km_s,
            v_dep_km_s,
            v_arr_km_s,
            t_dep_seed_s,
            t_arr_seed_s,
            nrev_signed_eval,
            dV_lev_grid_km_s,
            cfg.lambert_mu_km3_s2,
            obj_type=1,
            max_vinf0_km_s=max_vinf0_solve_arc,
            max_vinff_km_s=max_vinff_solve_arc,
            additional_args=None,
            debug=False,
            lev_type=cfg.lev_type,
            case_chunk_size=max(1, int(cfg.chunk_size)),
            return_endpoint_velocities=False,
        )

        arc_store = np.asarray(arc_store, dtype=np.int64).reshape(-1)
        dV_lev_all = np.asarray(dV_lev_all, dtype=float).reshape(-1)
        vinfD_km_s_all = np.asarray(vinfD_km_s_all, dtype=float).reshape(-1, 3)
        vinfA_km_s_all = np.asarray(vinfA_km_s_all, dtype=float).reshape(-1, 3)
        eta_lev_all = np.asarray(eta_store, dtype=float).reshape(-1)

        source_rows_eval = source_idx[arc_store]
        dep_rows_eval = dep_rows_chunk[source_rows_eval]
        arr_rows_eval = arr_rows_chunk[source_rows_eval]
        n_rev_eval_rows = nrev_signed_eval[arc_store]
    else:
        dep_rows_eval = dep_rows_chunk[source_idx]
        arr_rows_eval = arr_rows_chunk[source_idx]
        dV_lev_all = np.zeros(source_idx.shape[0], dtype=float)
        vinfD_km_s_all = v_dep_km_s - v_body_dep_km_s[source_idx]
        vinfA_km_s_all = v_arr_km_s - v_body_arr_km_s[source_idx]
        eta_lev_all = np.full(source_idx.shape[0], 0.5, dtype=float)
        n_rev_eval_rows = nrev_signed_eval

    dep_rows_res = np.empty(0, dtype=np.int64)
    arr_rows_res = np.empty(0, dtype=np.int64)
    dt_res_s = np.empty(0, dtype=float)
    vinfD_res_km_s = np.empty((0, 3), dtype=float)
    vinfA_res_km_s = np.empty((0, 3), dtype=float)
    n_rev_res = np.empty(0, dtype=np.int64)

    if bool(cfg.resonant_enabled):
        from star.resonant import generate_resonant_rows

        (
            dep_rows_res,
            arr_rows_res,
            dt_res_s,
            vinfD_res_km_s,
            vinfA_res_km_s,
            n_rev_res,
        ) = generate_resonant_rows(
            dep_rows_seed=dep_rows_seed,
            arr_rows_seed=arr_rows_seed,
            dt_seed_s=dt_seed_s,
            r_dep_seed_km=r_dep_seed_km,
            r_arr_seed_km=r_arr_seed_km,
            v_body_dep_seed_km_s=v_body_dep_seed_km_s,
            v_body_arr_seed_km_s=v_body_arr_seed_km_s,
            v_dep_seed_km_s=v_dep_km_s,
            v_arr_seed_km_s=v_arr_km_s,
            nrev_signed_seed=nrev_signed_eval,
            vinf_min_km_s=vinfD_min_km_s,
            vinf_max_km_s=vinfD_max_km_s,
            dvinf_km_s=float(cfg.resonant_dvinf_km_s),
            angle_tol_deg=float(cfg.resonant_angle_tol_deg),
            crank_angles_rad=cfg.resonant_crank_angles_rad,
        )
    if dep_rows_res.size > 0:
        dep_rows_eval = np.concatenate((dep_rows_eval, dep_rows_res))
        arr_rows_eval = np.concatenate((arr_rows_eval, arr_rows_res))
        dV_lev_all = np.concatenate((dV_lev_all, np.zeros(dep_rows_res.size, dtype=float)))
        vinfD_km_s_all = np.concatenate((vinfD_km_s_all, vinfD_res_km_s), axis=0)
        vinfA_km_s_all = np.concatenate((vinfA_km_s_all, vinfA_res_km_s), axis=0)
        eta_lev_all = np.concatenate((eta_lev_all, np.full(dep_rows_res.size, 0.5, dtype=float)))
        n_rev_eval_rows = np.concatenate((n_rev_eval_rows, n_rev_res))

    solved_mask = np.all(np.isfinite(vinfD_km_s_all), axis=1)
    solved_mask &= np.all(np.isfinite(vinfA_km_s_all), axis=1)
    solved_mask &= np.isfinite(dV_lev_all)
    solved_mask &= np.isfinite(eta_lev_all)

    vinfD_sq_km_s2 = np.sum(vinfD_km_s_all * vinfD_km_s_all, axis=1)
    vinfA_sq_km_s2 = np.sum(vinfA_km_s_all * vinfA_km_s_all, axis=1)

    vinf_mask = np.ones(vinfD_sq_km_s2.shape[0], dtype=bool)
    if np.isfinite(vinfD_min_km_s):
        vinf_mask &= vinfD_sq_km_s2 >= float(vinfD_min_km_s) ** 2
    if np.isfinite(vinfD_max_km_s):
        vinf_mask &= vinfD_sq_km_s2 <= float(vinfD_max_km_s) ** 2
    if np.isfinite(vinfA_min_km_s):
        vinf_mask &= vinfA_sq_km_s2 >= float(vinfA_min_km_s) ** 2
    if np.isfinite(vinfA_max_km_s):
        vinf_mask &= vinfA_sq_km_s2 <= float(vinfA_max_km_s) ** 2

    keep_mask = solved_mask & vinf_mask
    if not np.any(keep_mask):
        return None

    kept_dep_rows = dep_rows_eval[keep_mask]
    kept_arr_rows = arr_rows_eval[keep_mask]
    base_rows = {
        "ID": dep_data["IE"][kept_dep_rows].astype(np.int64, copy=False),
        "IA": arr_data["IE"][kept_arr_rows].astype(np.int64, copy=False),
        "vinfD_km_s": vinfD_km_s_all[keep_mask],
        "vinfA_km_s": vinfA_km_s_all[keep_mask],
        "n_rev": n_rev_eval_rows[keep_mask],
        "dv_lev_km_s": dV_lev_all[keep_mask],
        "eta_lev": eta_lev_all[keep_mask],
    }
    return base_rows


def encounter_filter(
    enc_db: EncounterDB,
    leg_dbs: Sequence[LegDatabase],
    *,
    stages: Optional[Sequence[int]] = None,
) -> EncounterDB:
    """Prune EncounterDB entries not used by provided leg databases.

    Invariants:
    - Original encounter ordering is preserved.
    - Encounter IDs (`IE`) are treated as immutable and are not renumbered.
    - `stage_to_entry_ids` and `entry_by_id` are rebuilt for the filtered set.
    - If `stages` is provided, pruning is only applied to those stage IDs.
    """

    if len(leg_dbs) == 0:
        raise ValueError("Encounter filtering requires at least one LegDatabase.")

    all_ie = np.asarray([int(entry.IE) for entry in enc_db.entries], dtype=np.int64)
    all_stage_ids = np.asarray([int(entry.stage_id) for entry in enc_db.entries], dtype=np.int64)

    used_chunks: List[np.ndarray] = []
    for leg_db in leg_dbs:
        used_chunks.append(np.asarray(leg_db.ID, dtype=np.int64).ravel())
        used_chunks.append(np.asarray(leg_db.IA, dtype=np.int64).ravel())

    used = np.unique(np.concatenate(used_chunks)) if used_chunks else np.empty(0, dtype=np.int64)
    if used.size == 0:
        raise ValueError("Encounter filtering received no used encounter IDs from leg databases.")

    used_present_mask = np.isin(used, all_ie)
    if not np.all(used_present_mask):
        missing = used[~used_present_mask]
        raise ValueError(f"Leg database references encounter IDs not present in EncounterDB: {missing.tolist()}")

    if stages is None:
        prune_stage_ids = np.unique(all_stage_ids)
    else:
        prune_stage_ids = np.asarray([int(stage_id) for stage_id in stages], dtype=np.int64)

    prune_stage_mask = np.isin(all_stage_ids, prune_stage_ids)
    used_mask = np.isin(all_ie, used)
    keep_mask = (~prune_stage_mask) | used_mask

    kept_entries = [entry for entry, keep in zip(enc_db.entries, keep_mask) if bool(keep)]

    stage_to_entry_ids: Dict[Tuple[int, int], List[int]] = {
        (int(stage_id), int(body_id)): [] for stage_id, body_id in enc_db.stage_to_entry_ids.keys()
    }
    entry_by_id: Dict[int, EncounterEntry] = {}

    for entry in kept_entries:
        key = (int(entry.stage_id), int(entry.body))
        if key not in stage_to_entry_ids:
            stage_to_entry_ids[key] = []
        stage_to_entry_ids[key].append(int(entry.IE))
        entry_by_id[int(entry.IE)] = entry

    filtered_db = EncounterDB(
        entries=kept_entries,
        stage_to_entry_ids=stage_to_entry_ids,
        entry_by_id=entry_by_id,
    )

    return filtered_db


def build_leg_db(
    enc_db: EncounterDB,
    cfg: LegBuildConfig,
    stage_arrays_cache: Optional[Dict[int, Dict[str, np.ndarray]]] = None,
) -> LegDatabase:
    """Build ballistic leg database for one stage transition `dep_stage_id -> arr_stage_id`.

    The function uses only encounter states already present in `enc_db`; no ephemeris
    re-query occurs here.
    """

    if int(cfg.leg_stage_id) != int(cfg.dep_stage_id):
        raise ValueError("leg_stage_id must match dep_stage_id for this builder.")
    if int(cfg.arr_stage_id) != int(cfg.dep_stage_id) + 1:
        raise ValueError("arr_stage_id must be dep_stage_id + 1.")

    tof_min_s = float(cfg.tof_min_s)
    tof_max_s = float(cfg.tof_max_s)
    if np.isfinite(tof_min_s) and np.isfinite(tof_max_s) and tof_max_s < tof_min_s:
        raise ValueError("tof_max_s must be >= tof_min_s.")

    vinfD_min_km_s, vinfD_max_km_s = map(float, cfg.vinfD_bounds_km_s)
    vinfA_min_km_s, vinfA_max_km_s = map(float, cfg.vinfA_bounds_km_s)
    if vinfD_max_km_s < vinfD_min_km_s:
        raise ValueError("vinfD upper bound must be >= lower bound.")
    if vinfA_max_km_s < vinfA_min_km_s:
        raise ValueError("vinfA upper bound must be >= lower bound.")
    if int(cfg.lambert_hz) not in (-1, 0, 1):
        raise ValueError("lambert_hz must be one of {-1, 0, 1}.")
    if bool(cfg.resonant_enabled) and (not np.isfinite(vinfD_min_km_s) or not np.isfinite(vinfD_max_km_s)):
        raise ValueError("Resonant sampling requires finite departure v-infinity bounds.")
    dV_lev_grid_km_s = _build_dv_lev_grid_km_s(float(cfg.dvlev_max_km_s), float(cfg.delta_dvlev_km_s))

    dep_data = _get_stage_arrays(enc_db, cfg.dep_stage_id, stage_arrays_cache)
    arr_data = _get_stage_arrays(enc_db, cfg.arr_stage_id, stage_arrays_cache)

    dep_t_et_s, arr_t_et_s, lower_dt_s, _upper_dt_s, lower_dt_strict, _use_tof_max, candidate_counts = _prepare_candidate_pair_counts(
        dep_data["t_et"],
        arr_data["t_et"],
        tof_min_s,
        tof_max_s,
        float(cfg.dt_positive_tol_s),
    )
    num_candidates_considered = int(np.sum(candidate_counts, dtype=np.int64))

    if num_candidates_considered == 0:
        return _empty_leg_db(cfg.leg_stage_id)

    nrev_max = int(max(cfg.lambert_nrev_max, 0))
    if int(cfg.lambert_hz) == 0:
        per_candidate_attempts = 2 + 4 * nrev_max
    else:
        per_candidate_attempts = 1 + 2 * nrev_max
    num_lambert_called = int(num_candidates_considered * per_candidate_attempts)
    total_lambert_outputs = 0
    out_parts: Dict[str, List[np.ndarray]] = {
        "ID": [],
        "IA": [],
        "vinfD_km_s": [],
        "vinfA_km_s": [],
        "n_rev": [],
        "dv_lev_km_s": [],
        "eta_lev": [],
    }
    candidate_chunk_size = max(1, int(cfg.chunk_size))
    for dep_rows_chunk, arr_rows_chunk, dt_candidates_chunk_s in _iter_candidate_pair_chunks_from_counts(
        dep_t_et_s,
        arr_t_et_s,
        lower_dt_s,
        lower_dt_strict,
        candidate_counts,
        chunk_size=candidate_chunk_size,
    ):

        r_dep_km = dep_data["r_km"][dep_rows_chunk]
        v_body_dep_km_s = dep_data["v_km_s"][dep_rows_chunk]
        r_arr_km = arr_data["r_km"][arr_rows_chunk]
        v_body_arr_km_s = arr_data["v_km_s"][arr_rows_chunk]

        # Leg database policy:
        # - sweep_rev is hardcoded to True
        # - lambert_nrev_max from problem is interpreted as max revolution count
        # - lambert_hz controls direction selection (+1/-1/0)
        v_dep_km_s, v_arr_km_s, nrev_signed_eval, source_idx = _solve_lambert_candidates(
            r_dep_km,
            r_arr_km,
            dt_candidates_chunk_s,
            cfg,
        )

        total_lambert_outputs += int(np.asarray(source_idx, dtype=np.int64).size)
        chunk_output = _process_lambert_chunk(
            dep_data=dep_data,
            arr_data=arr_data,
            dep_rows_chunk=dep_rows_chunk,
            arr_rows_chunk=arr_rows_chunk,
            dt_candidates_chunk_s=dt_candidates_chunk_s,
            r_dep_km=r_dep_km,
            r_arr_km=r_arr_km,
            v_body_dep_km_s=v_body_dep_km_s,
            v_body_arr_km_s=v_body_arr_km_s,
            v_dep_km_s=v_dep_km_s,
            v_arr_km_s=v_arr_km_s,
            nrev_signed_eval=nrev_signed_eval,
            source_idx=source_idx,
            cfg=cfg,
            dV_lev_grid_km_s=dV_lev_grid_km_s,
            vinfD_min_km_s=vinfD_min_km_s,
            vinfD_max_km_s=vinfD_max_km_s,
            vinfA_min_km_s=vinfA_min_km_s,
            vinfA_max_km_s=vinfA_max_km_s,
        )
        if chunk_output is None:
            continue
        for key, value in chunk_output.items():
            out_parts[key].append(value)

    num_lambert_failed = int(max(num_lambert_called - total_lambert_outputs, 0))

    if cfg.max_failure_frac is not None and num_lambert_called > 0:
        failure_frac = float(num_lambert_failed) / float(num_lambert_called)
        if failure_frac > float(cfg.max_failure_frac):
            raise RuntimeError(
                f"Lambert failure fraction {failure_frac:.6f} exceeded threshold {cfg.max_failure_frac:.6f}."
            )

    if not out_parts["ID"]:
        return _empty_leg_db(cfg.leg_stage_id)

    kept_ID = np.concatenate(out_parts["ID"], axis=0)
    kept_IA = np.concatenate(out_parts["IA"], axis=0)
    kept_vinfD_km_s = np.concatenate(out_parts["vinfD_km_s"], axis=0)
    kept_vinfA_km_s = np.concatenate(out_parts["vinfA_km_s"], axis=0)
    n_rev = np.concatenate(out_parts["n_rev"], axis=0)
    kept_dv_lev_km_s = np.concatenate(out_parts["dv_lev_km_s"], axis=0)
    kept_eta_lev = np.concatenate(out_parts["eta_lev"], axis=0)

    filtered_rows = _apply_custom_leg_filter(
        cfg,
        dep_data,
        arr_data,
        {
            "ID": kept_ID,
            "IA": kept_IA,
            "vinfD_km_s": kept_vinfD_km_s,
            "vinfA_km_s": kept_vinfA_km_s,
            "n_rev": n_rev,
            "dv_lev_km_s": kept_dv_lev_km_s,
            "eta_lev": kept_eta_lev,
        },
    )
    kept_ID = np.asarray(filtered_rows["ID"], dtype=np.int64)
    kept_IA = np.asarray(filtered_rows["IA"], dtype=np.int64)
    kept_vinfD_km_s = np.asarray(filtered_rows["vinfD_km_s"], dtype=float)
    kept_vinfA_km_s = np.asarray(filtered_rows["vinfA_km_s"], dtype=float)
    n_rev = np.asarray(filtered_rows["n_rev"], dtype=np.int64)
    kept_dv_lev_km_s = np.asarray(filtered_rows["dv_lev_km_s"], dtype=float)
    kept_eta_lev = np.asarray(filtered_rows["eta_lev"], dtype=float)

    if kept_ID.shape[0] == 0:
        return _empty_leg_db(cfg.leg_stage_id)

    num_legs_kept = int(kept_ID.shape[0])
    IL = np.arange(num_legs_kept, dtype=np.int64)

    leg_db = LegDatabase(
        IL=IL,
        stage_id=int(cfg.leg_stage_id),
        ID=kept_ID,
        IA=kept_IA,
        vinfD_km_s=kept_vinfD_km_s,
        vinfA_km_s=kept_vinfA_km_s,
        n_rev=n_rev,
        dv_lev_km_s=kept_dv_lev_km_s,
        eta_lev=kept_eta_lev,
    )

    if cfg.debug:
        assert leg_db.IL.ndim == 1
        assert leg_db.vinfD_km_s.shape == (leg_db.IL.size, 3)
        assert leg_db.vinfA_km_s.shape == (leg_db.IL.size, 3)
        assert np.all(np.isfinite(leg_db.vinfD_km_s))
        assert np.all(np.isfinite(leg_db.vinfA_km_s))
        assert leg_db.dv_lev_km_s.shape == (leg_db.IL.size,)
        assert np.all(np.isfinite(leg_db.dv_lev_km_s))
        assert leg_db.eta_lev.shape == (leg_db.IL.size,)
        assert np.all(np.isfinite(leg_db.eta_lev))

    return leg_db


def build_leg_stage_to_disk(
    enc_db: EncounterDB,
    cfg: LegBuildConfig,
    *,
    stage_dir: str | Path,
    stage_arrays_cache: Optional[Dict[int, Dict[str, np.ndarray]]] = None,
    post_rows: Optional[Dict[str, np.ndarray]] = None,
) -> int:
    """Build one leg stage and stream kept rows directly to disk."""

    from star.stage_db_npy import begin_leg_stage_writer

    if int(cfg.leg_stage_id) != int(cfg.dep_stage_id):
        raise ValueError("leg_stage_id must match dep_stage_id for this builder.")
    if int(cfg.arr_stage_id) != int(cfg.dep_stage_id) + 1:
        raise ValueError("arr_stage_id must be dep_stage_id + 1.")

    tof_min_s = float(cfg.tof_min_s)
    tof_max_s = float(cfg.tof_max_s)
    if np.isfinite(tof_min_s) and np.isfinite(tof_max_s) and tof_max_s < tof_min_s:
        raise ValueError("tof_max_s must be >= tof_min_s.")

    vinfD_min_km_s, vinfD_max_km_s = map(float, cfg.vinfD_bounds_km_s)
    vinfA_min_km_s, vinfA_max_km_s = map(float, cfg.vinfA_bounds_km_s)
    if vinfD_max_km_s < vinfD_min_km_s:
        raise ValueError("vinfD upper bound must be >= lower bound.")
    if vinfA_max_km_s < vinfA_min_km_s:
        raise ValueError("vinfA upper bound must be >= lower bound.")
    if int(cfg.lambert_hz) not in (-1, 0, 1):
        raise ValueError("lambert_hz must be one of {-1, 0, 1}.")
    if bool(cfg.resonant_enabled) and (not np.isfinite(vinfD_min_km_s) or not np.isfinite(vinfD_max_km_s)):
        raise ValueError("Resonant sampling requires finite departure v-infinity bounds.")
    dV_lev_grid_km_s = _build_dv_lev_grid_km_s(float(cfg.dvlev_max_km_s), float(cfg.delta_dvlev_km_s))

    dep_data = _get_stage_arrays(enc_db, cfg.dep_stage_id, stage_arrays_cache)
    arr_data = _get_stage_arrays(enc_db, cfg.arr_stage_id, stage_arrays_cache)

    dep_t_et_s, arr_t_et_s, lower_dt_s, _upper_dt_s, lower_dt_strict, _use_tof_max, candidate_counts = _prepare_candidate_pair_counts(
        dep_data["t_et"],
        arr_data["t_et"],
        tof_min_s,
        tof_max_s,
        float(cfg.dt_positive_tol_s),
    )
    num_candidates_considered = int(np.sum(candidate_counts, dtype=np.int64))
    if num_candidates_considered == 0:
        writer = begin_leg_stage_writer(stage_dir, stage_id=int(cfg.leg_stage_id), il_start=0)
        try:
            if post_rows is not None and int(np.asarray(post_rows["ID"], dtype=np.int64).size) > 0:
                writer.append_rows(
                    id=np.asarray(post_rows["ID"], dtype=np.int64),
                    ia=np.asarray(post_rows["IA"], dtype=np.int64),
                    vinfD_km_s=np.asarray(post_rows["vinfD_km_s"], dtype=float),
                    vinfA_km_s=np.asarray(post_rows["vinfA_km_s"], dtype=float),
                    n_rev=np.asarray(post_rows["n_rev"], dtype=np.int64),
                    dv_lev_km_s=np.asarray(post_rows["dv_lev_km_s"], dtype=float),
                    eta_lev=np.asarray(post_rows["eta_lev"], dtype=float),
                )
            return int(writer.finalize())
        except Exception:
            writer.abort()
            raise

    nrev_max = int(max(cfg.lambert_nrev_max, 0))
    if int(cfg.lambert_hz) == 0:
        per_candidate_attempts = 2 + 4 * nrev_max
    else:
        per_candidate_attempts = 1 + 2 * nrev_max
    num_lambert_called = int(num_candidates_considered * per_candidate_attempts)
    total_lambert_outputs = 0
    candidate_chunk_size = max(1, int(cfg.chunk_size))
    writer = begin_leg_stage_writer(stage_dir, stage_id=int(cfg.leg_stage_id), il_start=0)
    collected_parts: Optional[Dict[str, List[np.ndarray]]] = None
    if cfg.leg_filter is not None:
        collected_parts = {
            "ID": [],
            "IA": [],
            "vinfD_km_s": [],
            "vinfA_km_s": [],
            "n_rev": [],
            "dv_lev_km_s": [],
            "eta_lev": [],
        }
    try:
        for dep_rows_chunk, arr_rows_chunk, dt_candidates_chunk_s in _iter_candidate_pair_chunks_from_counts(
            dep_t_et_s,
            arr_t_et_s,
            lower_dt_s,
            lower_dt_strict,
            candidate_counts,
            chunk_size=candidate_chunk_size,
        ):
            r_dep_km = dep_data["r_km"][dep_rows_chunk]
            v_body_dep_km_s = dep_data["v_km_s"][dep_rows_chunk]
            r_arr_km = arr_data["r_km"][arr_rows_chunk]
            v_body_arr_km_s = arr_data["v_km_s"][arr_rows_chunk]

            v_dep_km_s, v_arr_km_s, nrev_signed_eval, source_idx = _solve_lambert_candidates(
                r_dep_km,
                r_arr_km,
                dt_candidates_chunk_s,
                cfg,
            )

            total_lambert_outputs += int(np.asarray(source_idx, dtype=np.int64).size)
            chunk_output = _process_lambert_chunk(
                dep_data=dep_data,
                arr_data=arr_data,
                dep_rows_chunk=dep_rows_chunk,
                arr_rows_chunk=arr_rows_chunk,
                dt_candidates_chunk_s=dt_candidates_chunk_s,
                r_dep_km=r_dep_km,
                r_arr_km=r_arr_km,
                v_body_dep_km_s=v_body_dep_km_s,
                v_body_arr_km_s=v_body_arr_km_s,
                v_dep_km_s=v_dep_km_s,
                v_arr_km_s=v_arr_km_s,
                nrev_signed_eval=nrev_signed_eval,
                source_idx=source_idx,
                cfg=cfg,
                dV_lev_grid_km_s=dV_lev_grid_km_s,
                vinfD_min_km_s=vinfD_min_km_s,
                vinfD_max_km_s=vinfD_max_km_s,
                vinfA_min_km_s=vinfA_min_km_s,
                vinfA_max_km_s=vinfA_max_km_s,
            )
            if chunk_output is None:
                continue
            if collected_parts is None:
                writer.append_rows(
                    id=np.asarray(chunk_output["ID"], dtype=np.int64),
                    ia=np.asarray(chunk_output["IA"], dtype=np.int64),
                    vinfD_km_s=np.asarray(chunk_output["vinfD_km_s"], dtype=float),
                    vinfA_km_s=np.asarray(chunk_output["vinfA_km_s"], dtype=float),
                    n_rev=np.asarray(chunk_output["n_rev"], dtype=np.int64),
                    dv_lev_km_s=np.asarray(chunk_output["dv_lev_km_s"], dtype=float),
                    eta_lev=np.asarray(chunk_output["eta_lev"], dtype=float),
                )
            else:
                for key, value in chunk_output.items():
                    collected_parts[key].append(value)

        num_lambert_failed = int(max(num_lambert_called - total_lambert_outputs, 0))
        if cfg.max_failure_frac is not None and num_lambert_called > 0:
            failure_frac = float(num_lambert_failed) / float(num_lambert_called)
            if failure_frac > float(cfg.max_failure_frac):
                raise RuntimeError(
                    f"Lambert failure fraction {failure_frac:.6f} exceeded threshold {cfg.max_failure_frac:.6f}."
                )

        if collected_parts is not None and collected_parts["ID"]:
            filtered_rows = _apply_custom_leg_filter(
                cfg,
                dep_data,
                arr_data,
                {
                    "ID": np.concatenate(collected_parts["ID"], axis=0),
                    "IA": np.concatenate(collected_parts["IA"], axis=0),
                    "vinfD_km_s": np.concatenate(collected_parts["vinfD_km_s"], axis=0),
                    "vinfA_km_s": np.concatenate(collected_parts["vinfA_km_s"], axis=0),
                    "n_rev": np.concatenate(collected_parts["n_rev"], axis=0),
                    "dv_lev_km_s": np.concatenate(collected_parts["dv_lev_km_s"], axis=0),
                    "eta_lev": np.concatenate(collected_parts["eta_lev"], axis=0),
                },
            )
            if int(np.asarray(filtered_rows["ID"], dtype=np.int64).size) > 0:
                writer.append_rows(
                    id=np.asarray(filtered_rows["ID"], dtype=np.int64),
                    ia=np.asarray(filtered_rows["IA"], dtype=np.int64),
                    vinfD_km_s=np.asarray(filtered_rows["vinfD_km_s"], dtype=float),
                    vinfA_km_s=np.asarray(filtered_rows["vinfA_km_s"], dtype=float),
                    n_rev=np.asarray(filtered_rows["n_rev"], dtype=np.int64),
                    dv_lev_km_s=np.asarray(filtered_rows["dv_lev_km_s"], dtype=float),
                    eta_lev=np.asarray(filtered_rows["eta_lev"], dtype=float),
                )

        if post_rows is not None and int(np.asarray(post_rows["ID"], dtype=np.int64).size) > 0:
            writer.append_rows(
                id=np.asarray(post_rows["ID"], dtype=np.int64),
                ia=np.asarray(post_rows["IA"], dtype=np.int64),
                vinfD_km_s=np.asarray(post_rows["vinfD_km_s"], dtype=float),
                vinfA_km_s=np.asarray(post_rows["vinfA_km_s"], dtype=float),
                n_rev=np.asarray(post_rows["n_rev"], dtype=np.int64),
                dv_lev_km_s=np.asarray(post_rows["dv_lev_km_s"], dtype=float),
                eta_lev=np.asarray(post_rows["eta_lev"], dtype=float),
            )
        return int(writer.finalize())
    except Exception:
        writer.abort()
        raise


if __name__ == "__main__":
    
    # Demo: load example/earth_to_jupiter.py, build EncounterDB, then build LegDBs.
    repo_root = Path(__file__).resolve().parent.parent
    metakernel_path = repo_root / "star" / "METAKERN.tm"
    if not metakernel_path.exists():
        raise FileNotFoundError(f"Meta-kernel not found: {metakernel_path}")

    spice.kclear()
    spice.furnsh(str(metakernel_path))
    print(f"Loaded SPICE metakernel: {metakernel_path}")

    import example.earth_to_jupiter as example

    bodies_by_stage = [list(stage_bodies) for stage_bodies in example.Body]
    time_bounds_days = np.asarray(example.Time, dtype=float)
    tof_min_days = np.asarray(example.tof_min, dtype=float)
    tof_max_days = np.asarray(example.tof_max, dtype=float)
    dt_days_by_stage = np.asarray(example.dt, dtype=float)
    alt_km_by_stage = list(example.alt)
    vlim = np.asarray(example.vlim, dtype=float)

    # clean up the tof / time bounds with LPs
    tightened_bounds_days = tighten_stage_time_bounds_days(time_bounds_days, tof_min_days, tof_max_days)
    if not np.all(np.isfinite(tightened_bounds_days)):
        raise ValueError("Encounter stage bounds remain infinite after tightening.")

    # build encounter database
    stage_configs: List[EncounterStageConfig] = []
    for stage_id, stage_bodies in enumerate(bodies_by_stage):
        dt_days = float(dt_days_by_stage[stage_id])
        if dt_days <= 0.0:
            raise ValueError(f"dt must be positive days for stage {stage_id}, got {dt_days}.")

        t_min_days = float(tightened_bounds_days[stage_id, 0])
        t_max_days = float(tightened_bounds_days[stage_id, 1])
        amin_default_km = float(alt_km_by_stage[stage_id])
        amin_km_map = {int(body_id): amin_default_km for body_id in stage_bodies}

        stage_configs.append(
            EncounterStageConfig(
                stage_id=int(stage_id),
                bodies=[int(body_id) for body_id in stage_bodies],
                t_min_et=j2000_days_to_et_seconds(t_min_days),
                t_max_et=j2000_days_to_et_seconds(t_max_days),
                dt_et=j2000_days_to_et_seconds(dt_days),
                amin_km=amin_km_map,
            )
        )

    enc_cfg = EncounterDBConfig(
        stages=stage_configs,
        frame=DEFAULT_FRAME,
        observer=DEFAULT_OBSERVER,
    )
    encounter_db = build_encounter_database(enc_cfg)
    print(f"EncounterDB entries: {len(encounter_db.entries)}")

    # build leg databases with lambert solver
    lambert_mu_km3_s2 = float(get_gm("10")[0])
    n_stages = len(bodies_by_stage)
    n_legs = n_stages - 1
    all_leg_dbs: List[LegDatabase] = []

    nrev_raw = getattr(example, "Nrev", None)
    if nrev_raw is None:
        nrev_raw = getattr(example, "lambert_nrev", [0] * n_legs)
    hz_raw = getattr(example, "lambert_hz", [1] * n_legs)
    dvlev_max_raw = getattr(example, "dVlev_max", None)
    if dvlev_max_raw is None:
        dvlev_max_raw = getattr(example, "dvlev_max", [0.0] * n_legs)
    delta_dvlev_raw = getattr(example, "delta_dvlev", [0.0] * n_legs)
    vinf_margin_pre_filter_raw = getattr(example, "vinf_margin_pre_filter", None)
    if vinf_margin_pre_filter_raw is None:
        vinf_margin_pre_filter_raw = getattr(example, "vinf_margin_pre_filter_km_s", 10.0)
    lev_type_raw = getattr(example, "lev_type", ["+-", "-+"])

    if np.isscalar(nrev_raw):
        nrev_by_leg = [int(nrev_raw)] * n_legs
    else:
        nrev_by_leg = [int(v) for v in list(nrev_raw)]
    if len(nrev_by_leg) < n_legs:
        raise ValueError(f"Need at least {n_legs} Lambert Nrev entries.")

    if np.isscalar(hz_raw):
        hz_by_leg = [int(hz_raw)] * n_legs
    else:
        hz_by_leg = [int(v) for v in list(hz_raw)]
    if len(hz_by_leg) < n_legs:
        raise ValueError(f"Need at least {n_legs} Lambert hz entries.")

    if np.isscalar(dvlev_max_raw):
        dvlev_max_by_leg = [float(dvlev_max_raw)] * n_legs
    else:
        dvlev_max_by_leg = [float(v) for v in list(dvlev_max_raw)]
    if len(dvlev_max_by_leg) < n_legs:
        raise ValueError(f"Need at least {n_legs} dVlev_max entries.")

    if np.isscalar(delta_dvlev_raw):
        delta_dvlev_by_leg = [float(delta_dvlev_raw)] * n_legs
    else:
        delta_dvlev_by_leg = [float(v) for v in list(delta_dvlev_raw)]
    if len(delta_dvlev_by_leg) < n_legs:
        raise ValueError(f"Need at least {n_legs} delta_dvlev entries.")

    if np.isscalar(vinf_margin_pre_filter_raw):
        vinf_margin_pre_filter_by_leg = [float(vinf_margin_pre_filter_raw)] * n_legs
    else:
        vinf_margin_pre_filter_by_leg = [float(v) for v in list(vinf_margin_pre_filter_raw)]
    if len(vinf_margin_pre_filter_by_leg) < n_legs:
        raise ValueError(f"Need at least {n_legs} vinf_margin_pre_filter entries.")

    if isinstance(lev_type_raw, str):
        lev_type = (lev_type_raw,)
    else:
        lev_type = tuple(str(v) for v in list(lev_type_raw))
    if len(lev_type) == 0:
        raise ValueError("example.lev_type must contain at least one entry.")

    for leg_index in range(n_legs):
        tof_min_s = j2000_days_to_et_seconds(float(tof_min_days[leg_index, leg_index + 1]))
        tof_max_s = j2000_days_to_et_seconds(float(tof_max_days[leg_index, leg_index + 1]))

        nrev_max = int(nrev_by_leg[leg_index])
        if nrev_max < 0:
            raise ValueError(f"example.lambert_nrev[{leg_index}] must be >= 0.")
        hz_leg = int(hz_by_leg[leg_index])
        if hz_leg not in (-1, 0, 1):
            raise ValueError(f"example.lambert_hz[{leg_index}] must be one of -1, 0, 1.")

        cfg = LegBuildConfig(
            leg_stage_id=int(leg_index),
            dep_stage_id=int(leg_index),
            arr_stage_id=int(leg_index + 1),
            tof_min_s=float(tof_min_s),
            tof_max_s=float(tof_max_s),
            vinfD_bounds_km_s=(float(vlim[0, leg_index]), float(vlim[1, leg_index])),
            vinfA_bounds_km_s=(float(vlim[0, leg_index + 1]), float(vlim[1, leg_index + 1])),
            lambert_mu_km3_s2=lambert_mu_km3_s2,
            lambert_nrev_max=int(nrev_max),
            lambert_hz=int(hz_leg),
            dvlev_max_km_s=float(dvlev_max_by_leg[leg_index]),
            delta_dvlev_km_s=float(delta_dvlev_by_leg[leg_index]),
            vinf_margin_pre_filter_km_s=float(vinf_margin_pre_filter_by_leg[leg_index]),
            lev_type=lev_type,
            parallelism=None,
            dt_positive_tol_s=1e-6,
            max_failure_frac=None,
            debug=False,
            chunk_size=20000,
        )

        leg_db = build_leg_db(encounter_db, cfg)
        all_leg_dbs.append(leg_db)

        print()
        print(f"Leg {leg_index} summary: kept={int(leg_db.IL.size)}")
        print(
            f"{'IL':>6} {'stage':>6} {'ID':>6} {'IA':>6} {'depB':>6} {'arrB':>6} "
            f"{'tD_day':>12} {'tA_day':>12} {'dt_day':>10} "
            f"{'|vinfD|':>10} {'|vinfA|':>10} {'hx':>12} {'hy':>12} {'hz':>12}"
        )
        print("-" * 136)

        max_rows_to_print = min(50, int(leg_db.IL.size))
        for row in range(max_rows_to_print):
            dep_entry = encounter_db.get_entry(int(leg_db.ID[row]))
            arr_entry = encounter_db.get_entry(int(leg_db.IA[row]))
            vinfD_norm = float(np.linalg.norm(leg_db.vinfD_km_s[row]))
            vinfA_norm = float(np.linalg.norm(leg_db.vinfA_km_s[row]))
            dt_days = float(arr_entry.t_et - dep_entry.t_et) / 86400.0
            h_leg_km2_s = np.cross(
                np.asarray(dep_entry.r_km, dtype=float),
                np.asarray(dep_entry.v_km_s, dtype=float) + np.asarray(leg_db.vinfD_km_s[row], dtype=float),
            )
            print(
                f"{int(leg_db.IL[row]):6d} {int(leg_db.stage_id):6d} "
                f"{int(leg_db.ID[row]):6d} {int(leg_db.IA[row]):6d} "
                f"{int(dep_entry.body):6d} {int(arr_entry.body):6d} "
                f"{et_seconds_to_j2000_days(float(dep_entry.t_et)):12.4f} "
                f"{et_seconds_to_j2000_days(float(arr_entry.t_et)):12.4f} "
                f"{dt_days:10.4f} "
                f"{vinfD_norm:10.4f} {vinfA_norm:10.4f} "
                f"{float(h_leg_km2_s[0]):12.4f} "
                f"{float(h_leg_km2_s[1]):12.4f} "
                f"{float(h_leg_km2_s[2]):12.4f}"
            )
